// Converts the composed supergraph SDL into an ESM module so serverless
// deployment never needs the compose CLI or filesystem reads at runtime.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const meshRoot = join(here, '..');
const outDir = join(meshRoot, 'lib/generated');
mkdirSync(outDir, { recursive: true });

const sdl = readFileSync(join(outDir, 'supergraph.graphql'), 'utf8');
const ts = `// Generated by \`pnpm generate\` from supergraph.graphql. Do not edit.
export const supergraph = /* GraphQL */ \`
${sdl.trim().replace(/`/g, '\\`').replace(/\$\{/g, '\\${')}
\`;
`;

writeFileSync(join(outDir, 'supergraph.mjs'), ts);
console.log('Wrote lib/generated/supergraph.mjs');
